Repository megalan-association/quests, pull requests merged in 2024-02, with the labels that each got.

#46 added error checking to some backend routes
  src/server/api/routers/admin.ts
  src/server/api/routers/room.ts
  src/server/api/routers/task.ts
Labels: Backend

#48 Added Missing Functionality to some Admin Routes
  src/server/api/routers/admin.ts
Labels: Backend

#54 Create Page Layout and Header
  src/components/ProfileCard.tsx
  src/components/joinSociety.tsx
  src/components/leaveSociety.tsx
  src/layout/Header.tsx
  src/pages/_layout.tsx
  src/pages/settings.tsx
Labels: Styling, Component

#57 Landing page
  package-lock.json
  package.json
  public/MegaLAN_Logo_Horizontal_Black.png
  public/MegaLAN_Logo_Horizontal_White.png
  src/components/icons/GiftIcon.tsx
  src/components/icons/TrophyIcon.tsx
  src/components/icons/UserIcon.tsx
  src/pages/landing.tsx
Labels: Page

#58 Completed Room Pages
  src/components/CompleteTaskModal.tsx
  src/components/SeeMore.tsx
  src/components/TaskCard.tsx
  src/components/statusProgressBar.tsx
  src/layout/Header.tsx
  src/pages/rooms/[id].tsx
  src/server/api/routers/room.ts
Labels: Modal, Page, Component

#59 Created Admin Complete Task Page and Participant Complete Task Modal
  package-lock.json
  package.json
  src/components/CompleteTaskModal.tsx
  src/components/Scanner.tsx
  src/components/TaskCard.tsx
  src/pages/admin/scan-qr-code.tsx
  src/pages/rooms/[id].tsx
  src/server/api/routers/room.ts
  src/server/api/routers/user.ts
  src/styles/globals.css
Labels: Modal, Page, Backend, Component

#60 Made QR Code modal automatically Close on Success and Display Toast
  src/components/CompleteTaskModal.tsx
  src/pages/admin/scan-qr-code.tsx
  src/pages/rooms/[id].tsx
  src/server/api/routers/user.ts
Labels: Modal, Page

#61 QR Code Scanner Bug Fix
  src/pages/admin/scan-qr-code.tsx
Labels: bug

#63 Added Admin View to Task Card
  src/components/TaskCard.tsx
  src/pages/rooms/[id].tsx
Labels: Component

#65 Added Admin Task Backend Route and Modified Admin Task Card to Include Activate
  src/components/TaskCard.tsx
  src/pages/rooms/[id].tsx
  src/server/api/routers/admin.ts
  src/server/api/routers/room.ts
  src/server/api/routers/task.ts
Labels: Backend, Component

#67 Added Third Party Auth Methods
  .env.example
  src/env.js
  src/server/auth.ts
Labels: Page

#71 Minor Updates to Everything 🚀
  public/megalan_logo.png
  src/components/ProfileCard.tsx
  src/components/unauthorized.tsx
  src/layout/Header.tsx
  src/pages/admin/manage-tasks.tsx
  src/pages/admin/scan-qr-code.tsx
  src/pages/index.tsx
  src/pages/landing.tsx
  src/pages/leaderboard.tsx
  src/pages/rooms/[id].tsx
  src/server/api/routers/progress.ts
Labels: bug, enhancement, Styling

#72 Updated DB Schema
  prisma/schema.prisma
  public/seb-open-area.jpg
Labels: bug

#74 style fixes
  src/components/ParticipantDashboard.tsx
  src/components/TaskCard.tsx
  src/layout/Header.tsx
  src/pages/rooms/[id].tsx
Labels: Styling
